-- ============================================================================
-- CHILL & CHOC RETAIL - COMPLETE ENTERPRISE SUPABASE / POSTGRESQL SCHEMA
-- Generated by Database Administrator
-- ============================================================================
-- Features:
--  1. Fully Normalized Core Tables with Foreign Keys & Constraints
--  2. UUID Primary Keys with Automatic Generation
--  3. Automated updated_at Timestamp Triggers
--  4. Optimized B-Tree Indexes for POS, Filtering & Financial Reporting
--  5. Full Realtime Replication Enablement (REPLICA IDENTITY FULL)
--  6. Pre-configured Row Level Security (RLS) Policies
--  7. Analytical SQL Views for Financial, Inventory & Staff Reporting
--  8. Comprehensive Initial Seed Data matching Chill & Choc System
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 0. EXTENSIONS & PREREQUISITES
-- ----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Function: Automatic updated_at timestamp maintenance
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------------------------------------------------------
-- 1. OPERATORS & TERMINAL AUTHENTICATION
-- ----------------------------------------------------------------------------
-- Manages Admin, Manager, and Cashier terminal credentials with PIN & password
CREATE TABLE IF NOT EXISTS operators (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(150) NOT NULL,
    handle VARCHAR(60) UNIQUE NOT NULL, -- e.g. "@admin", "@cashier", "@manager"
    email VARCHAR(255) UNIQUE,
    password_hash TEXT, -- Stored hash or password for Admin & Manager logins
    role VARCHAR(30) NOT NULL CHECK (role IN ('ADMIN', 'MANAGER', 'CASHIER')),
    pin VARCHAR(10) NOT NULL, -- 4-digit security PIN e.g. "1234", "2580"
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Blocked')),
    avatar_color VARCHAR(30) DEFAULT 'teal' CHECK (avatar_color IN ('teal', 'gold', 'indigo', 'rose', 'slate')),
    notes TEXT,
    last_active_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TRIGGER trg_operators_updated_at
BEFORE UPDATE ON operators
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_operators_pin ON operators(pin);
CREATE INDEX idx_operators_handle ON operators(handle);
CREATE INDEX idx_operators_status ON operators(status);
CREATE INDEX idx_operators_role ON operators(role);

-- ----------------------------------------------------------------------------
-- 2. STORE OUTLETS & POS REGISTERS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS store_terminals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(50) UNIQUE NOT NULL, -- e.g. "POS-01", "POS-02"
    name VARCHAR(100) NOT NULL,       -- e.g. "Register 01 - Express Counter"
    outlet_name VARCHAR(150) NOT NULL DEFAULT 'Colombo Flagship Outlet',
    is_locked BOOLEAN NOT NULL DEFAULT false,
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Maintenance', 'Offline')),
    last_ping_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- ----------------------------------------------------------------------------
-- 3. CONFECTION CATEGORIES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS confection_categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug VARCHAR(60) UNIQUE NOT NULL, -- e.g. "chocolate", "toffees", "biscuits", "drinks", "gifts", "others"
    name VARCHAR(100) NOT NULL,       -- e.g. "Chocolates & Truffles"
    display_order INT DEFAULT 0,
    color_code VARCHAR(20) DEFAULT '#78350F',
    icon_name VARCHAR(50) DEFAULT 'Package',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- ----------------------------------------------------------------------------
-- 4. SUPPLIERS & VENDORS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS suppliers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(50) UNIQUE NOT NULL, -- e.g. "SUP-001", "CBS"
    name VARCHAR(200) NOT NULL,
    brand VARCHAR(150),
    contact_person VARCHAR(150),
    phone VARCHAR(50) NOT NULL,
    email VARCHAR(255),
    address TEXT,
    lead_time_days INT DEFAULT 3,
    rating NUMERIC(3,2) DEFAULT 5.00,
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    since_date DATE,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TRIGGER trg_suppliers_updated_at
BEFORE UPDATE ON suppliers
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_suppliers_code ON suppliers(code);
CREATE INDEX idx_suppliers_status ON suppliers(status);

-- ----------------------------------------------------------------------------
-- 5. PRODUCTS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    sku VARCHAR(60) UNIQUE NOT NULL,
    barcode VARCHAR(100) UNIQUE NOT NULL,
    category_slug VARCHAR(60) NOT NULL REFERENCES confection_categories(slug) ON UPDATE CASCADE,
    weight VARCHAR(50),
    price NUMERIC(12,2) NOT NULL DEFAULT 0.00,       -- Current Retail Selling Price
    cost_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,  -- Standard / Default Wholesale Cost
    stock INT NOT NULL DEFAULT 0,                    -- Unified Total On-Hand Stock
    low_stock_threshold INT NOT NULL DEFAULT 5,
    brand VARCHAR(150),
    image_url TEXT,
    description TEXT,
    is_available BOOLEAN NOT NULL DEFAULT true,
    supplier_id UUID REFERENCES suppliers(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_products_barcode ON products(barcode);
CREATE INDEX idx_products_sku ON products(sku);
CREATE INDEX idx_products_category ON products(category_slug);
CREATE INDEX idx_products_stock ON products(stock);

-- ----------------------------------------------------------------------------
-- 6. PRODUCT BATCHES & EXPIRY TRACKING
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_batches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    supplier_id UUID REFERENCES suppliers(id) ON DELETE SET NULL,
    supplier_name VARCHAR(200),
    batch_number VARCHAR(100) NOT NULL, -- e.g. "LOT-CBS-8803", "B-2026-09"
    cost_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    selling_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    quantity_received INT NOT NULL DEFAULT 0,
    quantity_remaining INT NOT NULL DEFAULT 0,
    received_date DATE NOT NULL DEFAULT CURRENT_DATE,
    expiry_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TRIGGER trg_product_batches_updated_at
BEFORE UPDATE ON product_batches
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_batches_product_id ON product_batches(product_id);
CREATE INDEX idx_batches_expiry_date ON product_batches(expiry_date);
CREATE INDEX idx_batches_quantity_remaining ON product_batches(quantity_remaining);

-- ----------------------------------------------------------------------------
-- 7. STAFF MEMBERS & FLOOR REPS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staff_members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(150) NOT NULL,
    nic VARCHAR(50),
    phone VARCHAR(50) NOT NULL,
    email VARCHAR(255),
    address TEXT,
    emergency_contact VARCHAR(150),
    role VARCHAR(80) NOT NULL DEFAULT 'Staff', -- e.g. "Cashier", "Manager", "Staff"
    attendances INT NOT NULL DEFAULT 0,
    base_salary NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    pay_frequency VARCHAR(30) NOT NULL DEFAULT 'Monthly' CHECK (pay_frequency IN ('Monthly', 'Bi-weekly', 'Weekly')),
    salary_date VARCHAR(50) DEFAULT '28th of Month',
    overtime_rate NUMERIC(10,2) NOT NULL DEFAULT 400.00,
    status VARCHAR(30) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive', 'On Leave')),
    bank_name VARCHAR(150),
    bank_account VARCHAR(80),
    bank_branch VARCHAR(150),
    joining_date DATE,
    monthly_sales_attributed NUMERIC(14,2) DEFAULT 0.00,
    is_paid_this_month BOOLEAN NOT NULL DEFAULT false,
    last_paid_date DATE,
    last_paid_amount NUMERIC(12,2),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TRIGGER trg_staff_members_updated_at
BEFORE UPDATE ON staff_members
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_staff_status ON staff_members(status);
CREATE INDEX idx_staff_role ON staff_members(role);

-- ----------------------------------------------------------------------------
-- 8. PAYROLL DISBURSEMENTS & SALARY SETTLEMENTS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payroll_disbursements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    staff_id UUID NOT NULL REFERENCES staff_members(id) ON DELETE CASCADE,
    staff_name VARCHAR(150) NOT NULL,
    role VARCHAR(80) NOT NULL,
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    disbursement_mode VARCHAR(50) NOT NULL DEFAULT 'Salary Settlement' CHECK (disbursement_mode IN ('Salary Settlement', 'Salary Advance')),
    basic_salary NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    overtime_hours NUMERIC(8,2) NOT NULL DEFAULT 0.00,
    overtime_rate NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    overtime_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    bonus_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    bonus_reason TEXT,
    deduction_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    deduction_reason TEXT,
    total_payable NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    payment_method VARCHAR(40) NOT NULL DEFAULT 'Bank Transfer' CHECK (payment_method IN ('Cash', 'Bank Transfer', 'Cheque')),
    bank_details TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_payroll_staff_id ON payroll_disbursements(staff_id);
CREATE INDEX idx_payroll_date ON payroll_disbursements(transaction_date);

-- ----------------------------------------------------------------------------
-- 9. CUSTOMERS & LOYALTY
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(150) NOT NULL DEFAULT 'Walk-in Customer',
    phone VARCHAR(50),
    email VARCHAR(255),
    is_walk_in BOOLEAN NOT NULL DEFAULT true,
    loyalty_points INT DEFAULT 0,
    total_spent NUMERIC(14,2) DEFAULT 0.00,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_customers_phone ON customers(phone);

-- ----------------------------------------------------------------------------
-- 10. CASH SESSIONS & TILL RECONCILIATION
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cash_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cashier_name VARCHAR(150) NOT NULL,
    operator_id UUID REFERENCES operators(id) ON DELETE SET NULL,
    register_code VARCHAR(50) NOT NULL DEFAULT 'POS-01',
    business_date DATE NOT NULL DEFAULT CURRENT_DATE,
    started_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    closed_at TIMESTAMPTZ,
    opening_cash NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    cash_sales NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    cash_refunds NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    cash_expenses NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    cash_in NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    cash_out NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    expected_cash NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    counted_cash NUMERIC(12,2),
    difference NUMERIC(12,2) DEFAULT 0.00, -- positive = over, negative = short
    difference_reason TEXT,
    is_closed BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_cash_sessions_business_date ON cash_sessions(business_date);
CREATE INDEX idx_cash_sessions_is_closed ON cash_sessions(is_closed);

-- ----------------------------------------------------------------------------
-- 11. CASH MOVEMENTS (PETTY CASH, EXPENSES, DRAWER FLOATS)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cash_movements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cash_session_id UUID REFERENCES cash_sessions(id) ON DELETE SET NULL,
    type VARCHAR(40) NOT NULL CHECK (type IN ('Cash In', 'Cash Out', 'Expense', 'Bank Drop', 'Petty Cash')),
    amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    reason VARCHAR(255) NOT NULL,
    reference VARCHAR(100),
    notes TEXT,
    cashier VARCHAR(150) NOT NULL,
    business_date DATE NOT NULL DEFAULT CURRENT_DATE,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_cash_movements_session_id ON cash_movements(cash_session_id);
CREATE INDEX idx_cash_movements_date ON cash_movements(business_date);
CREATE INDEX idx_cash_movements_type ON cash_movements(type);

-- ----------------------------------------------------------------------------
-- 12. SALES INVOICES & ORDERS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sales_invoices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_number VARCHAR(80) UNIQUE NOT NULL, -- e.g. "INV-001830"
    date_str VARCHAR(50) NOT NULL DEFAULT 'Today',
    sale_date DATE NOT NULL DEFAULT CURRENT_DATE,
    sale_time VARCHAR(30) NOT NULL,             -- e.g. "11:42 AM"
    timestamp TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    discount_total NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    tax NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    total NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    change_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    cashier_name VARCHAR(150) NOT NULL,
    operator_id UUID REFERENCES operators(id) ON DELETE SET NULL,
    salesperson_id UUID REFERENCES staff_members(id) ON DELETE SET NULL,
    salesperson_name VARCHAR(150),
    customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
    customer_name VARCHAR(150) DEFAULT 'Walk-in Customer',
    customer_phone VARCHAR(50),
    status VARCHAR(30) NOT NULL DEFAULT 'Completed' CHECK (status IN ('Completed', 'Refunded', 'Partially Refunded', 'Returned')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_sales_invoice_number ON sales_invoices(invoice_number);
CREATE INDEX idx_sales_sale_date ON sales_invoices(sale_date);
CREATE INDEX idx_sales_status ON sales_invoices(status);
CREATE INDEX idx_sales_salesperson ON sales_invoices(salesperson_id);

-- ----------------------------------------------------------------------------
-- 13. SALES ITEMS (LINE ITEMS)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sales_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_id UUID NOT NULL REFERENCES sales_invoices(id) ON DELETE CASCADE,
    product_id UUID REFERENCES products(id) ON DELETE SET NULL,
    product_name VARCHAR(255) NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    unit_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    cost_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    discount_type VARCHAR(20), -- 'percentage' | 'fixed'
    discount_value NUMERIC(10,2) DEFAULT 0.00,
    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    salesperson_id UUID REFERENCES staff_members(id) ON DELETE SET NULL,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_sales_items_invoice ON sales_items(invoice_id);
CREATE INDEX idx_sales_items_product ON sales_items(product_id);

-- ----------------------------------------------------------------------------
-- 14. SALES ITEM BATCH ALLOCATIONS (TRACEABILITY)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sales_item_batch_allocations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sales_item_id UUID NOT NULL REFERENCES sales_items(id) ON DELETE CASCADE,
    batch_id UUID REFERENCES product_batches(id) ON DELETE SET NULL,
    batch_number VARCHAR(100) NOT NULL,
    supplier_id UUID REFERENCES suppliers(id) ON DELETE SET NULL,
    supplier_name VARCHAR(200),
    quantity INT NOT NULL DEFAULT 1,
    cost_price NUMERIC(12,2) DEFAULT 0.00,
    expiry_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- ----------------------------------------------------------------------------
-- 15. PAYMENT TENDERS (MULTI-TENDER CHECKOUT)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payment_tenders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_id UUID NOT NULL REFERENCES sales_invoices(id) ON DELETE CASCADE,
    method VARCHAR(40) NOT NULL CHECK (method IN ('cash', 'card', 'bank_transfer', 'voucher', 'other')),
    amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    reference VARCHAR(150), -- e.g. "VISA-9941", "MASTER-4412", "CHQ-1002"
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_payment_tenders_invoice ON payment_tenders(invoice_id);
CREATE INDEX idx_payment_tenders_method ON payment_tenders(method);

-- ----------------------------------------------------------------------------
-- 16. HELD BILLS (PARKED TRANSACTIONS)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS held_bills (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    hold_code VARCHAR(50) UNIQUE NOT NULL, -- e.g. "HOLD-1042"
    items_count INT NOT NULL DEFAULT 1,
    total NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    cashier VARCHAR(150) NOT NULL,
    customer_name VARCHAR(150),
    customer_phone VARCHAR(50),
    note TEXT,
    items_payload JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- ----------------------------------------------------------------------------
-- 17. CUSTOMER RETURNS & EXCHANGES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS return_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    return_code VARCHAR(80) UNIQUE NOT NULL, -- e.g. "RET-0042"
    invoice_number VARCHAR(80) NOT NULL,
    invoice_id UUID REFERENCES sales_invoices(id) ON DELETE SET NULL,
    date_str VARCHAR(50) DEFAULT 'Today',
    timestamp TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    total_refund NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    resolution_type VARCHAR(40) NOT NULL CHECK (resolution_type IN ('refund', 'same_replacement', 'exchange')),
    exchange_product_id UUID REFERENCES products(id) ON DELETE SET NULL,
    exchange_product_name VARCHAR(255),
    exchange_unit_price NUMERIC(12,2) DEFAULT 0.00,
    exchange_quantity INT DEFAULT 0,
    exchange_total_value NUMERIC(12,2) DEFAULT 0.00,
    exchange_price_difference NUMERIC(12,2) DEFAULT 0.00,
    status VARCHAR(40) NOT NULL DEFAULT 'Pending Admin Approval' CHECK (status IN ('Pending Admin Approval', 'Approved', 'Rejected')),
    submitted_by VARCHAR(150) NOT NULL,
    reviewed_at TIMESTAMPTZ,
    reviewed_by VARCHAR(150),
    review_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS return_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    return_request_id UUID NOT NULL REFERENCES return_requests(id) ON DELETE CASCADE,
    product_id UUID REFERENCES products(id) ON DELETE SET NULL,
    product_name VARCHAR(255) NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    unit_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    reason VARCHAR(100) NOT NULL, -- e.g. "Damaged", "Expired", "Quality Issue", "Changed Mind"
    return_to_stock BOOLEAN NOT NULL DEFAULT false,
    refund_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    supplier_id UUID REFERENCES suppliers(id) ON DELETE SET NULL,
    supplier_name VARCHAR(200),
    batch_number VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_returns_status ON return_requests(status);
CREATE INDEX idx_returns_invoice ON return_requests(invoice_number);

-- ----------------------------------------------------------------------------
-- 18. SUPPLIER RETURNS (RTV CLAIMS & DEBIT NOTES)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS supplier_returns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    return_code VARCHAR(80) UNIQUE NOT NULL, -- e.g. "RTV-0042"
    supplier_id UUID NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,
    supplier_name VARCHAR(200) NOT NULL,
    customer_invoice_number VARCHAR(80),
    product_id UUID REFERENCES products(id) ON DELETE SET NULL,
    product_name VARCHAR(255) NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    unit_cost NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    total_debit_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    batch_number VARCHAR(100) NOT NULL,
    reason VARCHAR(60) NOT NULL CHECK (reason IN ('Damaged', 'Expired', 'Quality Issue', 'Customer Changed Mind', 'Wrong Product', 'Packaging Defect', 'Other')),
    claim_status VARCHAR(60) NOT NULL DEFAULT 'Pending Dispatch' CHECK (claim_status IN ('Pending Dispatch', 'Dispatched to Supplier', 'Credit Note Received', 'Replacement Received', 'Rejected by Supplier')),
    date_str VARCHAR(50),
    timestamp TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TRIGGER trg_supplier_returns_updated_at
BEFORE UPDATE ON supplier_returns
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_rtv_supplier_id ON supplier_returns(supplier_id);
CREATE INDEX idx_rtv_claim_status ON supplier_returns(claim_status);

-- ----------------------------------------------------------------------------
-- 19. PURCHASE ORDERS & MULTI-SUPPLIER RESTOCK
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS purchase_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    po_number VARCHAR(80) UNIQUE NOT NULL,   -- e.g. "PO-8803"
    invoice_ref VARCHAR(100) NOT NULL,        -- e.g. "CBS-4412"
    supplier_id UUID NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,
    supplier_name VARCHAR(200) NOT NULL,
    date VARCHAR(50) NOT NULL,               -- e.g. "Aug 27, 2026"
    po_date DATE NOT NULL DEFAULT CURRENT_DATE,
    time VARCHAR(30) NOT NULL,               -- e.g. "04:30 PM"
    is_rolled_over BOOLEAN NOT NULL DEFAULT false,
    total_invoiced NUMERIC(14,2) NOT NULL DEFAULT 0.00,
    total_paid NUMERIC(14,2) NOT NULL DEFAULT 0.00,
    balance_due NUMERIC(14,2) NOT NULL DEFAULT 0.00,
    payment_status VARCHAR(40) NOT NULL DEFAULT 'PAID' CHECK (payment_status IN ('PAID', 'CHEQUE PENDING', 'CREDIT', 'PARTIAL')),
    payment_cash NUMERIC(12,2) DEFAULT 0.00,
    payment_card NUMERIC(12,2) DEFAULT 0.00,
    payment_cheque NUMERIC(12,2) DEFAULT 0.00,
    cheque_due_date VARCHAR(50),
    cheque_number VARCHAR(100),
    cheque_status VARCHAR(30) CHECK (cheque_status IN ('PENDING', 'CLEARED', 'CANCELLED')),
    previous_cheque_number VARCHAR(100),
    unpaid_due_date VARCHAR(50),
    verified_by VARCHAR(150) NOT NULL DEFAULT 'Store Manager',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TRIGGER trg_purchase_orders_updated_at
BEFORE UPDATE ON purchase_orders
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS purchase_order_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    purchase_order_id UUID NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
    product_id UUID REFERENCES products(id) ON DELETE SET NULL,
    product_name VARCHAR(255) NOT NULL,
    weight VARCHAR(50),
    batch_number VARCHAR(100) NOT NULL,
    expiry_date VARCHAR(60),
    quantity INT NOT NULL DEFAULT 1,
    cost_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    selling_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_po_supplier_id ON purchase_orders(supplier_id);
CREATE INDEX idx_po_payment_status ON purchase_orders(payment_status);

-- ============================================================================
-- 20. ANALYTICAL DATABASE VIEWS FOR EXECUTIVE REPORTING
-- ============================================================================

-- View: Daily Sales Summary
CREATE OR REPLACE VIEW v_daily_sales_analytics AS
SELECT 
    si.sale_date,
    COUNT(si.id) AS total_bills,
    COALESCE(SUM(si.subtotal), 0) AS gross_revenue,
    COALESCE(SUM(si.discount_total), 0) AS total_discounts,
    COALESCE(SUM(si.total), 0) AS net_revenue,
    COALESCE(SUM(
        (SELECT SUM(s_item.cost_price * s_item.quantity) 
         FROM sales_items s_item 
         WHERE s_item.invoice_id = si.id)
    ), 0) AS total_cogs,
    COALESCE(SUM(si.total), 0) - COALESCE(SUM(
        (SELECT SUM(s_item.cost_price * s_item.quantity) 
         FROM sales_items s_item 
         WHERE s_item.invoice_id = si.id)
    ), 0) AS gross_profit
FROM sales_invoices si
WHERE si.status = 'Completed'
GROUP BY si.sale_date
ORDER BY si.sale_date DESC;

-- View: Stock Valuation & Inventory Capital
CREATE OR REPLACE VIEW v_product_stock_valuation AS
SELECT 
    p.id AS product_id,
    p.name AS product_name,
    p.sku,
    p.category_slug,
    p.stock AS quantity_on_hand,
    p.cost_price AS unit_cost,
    p.price AS unit_price,
    (p.stock * p.cost_price) AS total_cost_valuation,
    (p.stock * p.price) AS total_retail_valuation,
    ((p.stock * p.price) - (p.stock * p.cost_price)) AS unrealized_profit
FROM products p
ORDER BY total_retail_valuation DESC;

-- View: Batch Expiry Risk Exposure
CREATE OR REPLACE VIEW v_batch_expiry_risk AS
SELECT 
    pb.id AS batch_id,
    p.name AS product_name,
    p.sku,
    pb.batch_number,
    pb.supplier_name,
    pb.quantity_remaining,
    pb.cost_price,
    pb.selling_price,
    (pb.quantity_remaining * pb.cost_price) AS cost_at_risk,
    (pb.quantity_remaining * pb.selling_price) AS retail_at_risk,
    pb.expiry_date,
    (pb.expiry_date - CURRENT_DATE) AS days_remaining,
    CASE 
        WHEN (pb.expiry_date - CURRENT_DATE) <= 30 THEN 'CRITICAL (< 30d)'
        WHEN (pb.expiry_date - CURRENT_DATE) <= 60 THEN 'WARNING (30-60d)'
        ELSE 'SAFE (> 60d)'
    END AS risk_tier
FROM product_batches pb
JOIN products p ON pb.product_id = p.id
WHERE pb.quantity_remaining > 0
ORDER BY pb.expiry_date ASC;

-- View: Staff Sales Leaderboard
CREATE OR REPLACE VIEW v_staff_sales_leaderboard AS
SELECT 
    COALESCE(sm.id, si.salesperson_id) AS staff_id,
    COALESCE(sm.name, si.salesperson_name, 'Store Register') AS staff_name,
    COALESCE(sm.role, 'Floor Staff') AS role,
    COUNT(si.id) AS total_bills,
    COALESCE(SUM(
        (SELECT SUM(s_item.quantity) FROM sales_items s_item WHERE s_item.invoice_id = si.id)
    ), 0) AS total_units_sold,
    COALESCE(SUM(si.total), 0) AS total_attributed_sales
FROM sales_invoices si
LEFT JOIN staff_members sm ON si.salesperson_id = sm.id
WHERE si.status = 'Completed'
GROUP BY sm.id, sm.name, sm.role, si.salesperson_id, si.salesperson_name
ORDER BY total_attributed_sales DESC;

-- View: Outstanding Supplier Liabilities
CREATE OR REPLACE VIEW v_supplier_liabilities AS
SELECT 
    s.id AS supplier_id,
    s.code AS supplier_code,
    s.name AS supplier_name,
    COUNT(po.id) AS total_purchase_orders,
    COALESCE(SUM(po.total_invoiced), 0) AS total_invoiced,
    COALESCE(SUM(po.total_paid), 0) AS total_paid,
    COALESCE(SUM(po.balance_due), 0) AS total_outstanding_balance,
    COALESCE(SUM(CASE WHEN po.payment_status = 'CHEQUE PENDING' THEN po.payment_cheque ELSE 0 END), 0) AS pending_cheque_amount
FROM suppliers s
LEFT JOIN purchase_orders po ON s.id = po.supplier_id
GROUP BY s.id, s.code, s.name
ORDER BY total_outstanding_balance DESC;

-- ============================================================================
-- 21. SUPABASE REALTIME CONFIGURATION (FULL REPLICATION IDENTITY)
-- ============================================================================
-- Ensure all modified columns are broadcasted in update payloads
ALTER TABLE operators REPLICA IDENTITY FULL;
ALTER TABLE cash_sessions REPLICA IDENTITY FULL;
ALTER TABLE cash_movements REPLICA IDENTITY FULL;
ALTER TABLE sales_invoices REPLICA IDENTITY FULL;
ALTER TABLE sales_items REPLICA IDENTITY FULL;
ALTER TABLE return_requests REPLICA IDENTITY FULL;
ALTER TABLE products REPLICA IDENTITY FULL;
ALTER TABLE product_batches REPLICA IDENTITY FULL;
ALTER TABLE held_bills REPLICA IDENTITY FULL;
ALTER TABLE staff_members REPLICA IDENTITY FULL;
ALTER TABLE purchase_orders REPLICA IDENTITY FULL;

-- Add tables to the default Supabase realtime publication
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE operators;
        ALTER PUBLICATION supabase_realtime ADD TABLE cash_sessions;
        ALTER PUBLICATION supabase_realtime ADD TABLE cash_movements;
        ALTER PUBLICATION supabase_realtime ADD TABLE sales_invoices;
        ALTER PUBLICATION supabase_realtime ADD TABLE sales_items;
        ALTER PUBLICATION supabase_realtime ADD TABLE return_requests;
        ALTER PUBLICATION supabase_realtime ADD TABLE products;
        ALTER PUBLICATION supabase_realtime ADD TABLE product_batches;
        ALTER PUBLICATION supabase_realtime ADD TABLE held_bills;
        ALTER PUBLICATION supabase_realtime ADD TABLE staff_members;
        ALTER PUBLICATION supabase_realtime ADD TABLE purchase_orders;
    END IF;
END $$;

-- ============================================================================
-- 22. ROW-LEVEL SECURITY (RLS) POLICIES
-- ============================================================================
ALTER TABLE operators ENABLE ROW LEVEL SECURITY;
ALTER TABLE store_terminals ENABLE ROW LEVEL SECURITY;
ALTER TABLE confection_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_disbursements ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE cash_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE cash_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales_item_batch_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_tenders ENABLE ROW LEVEL SECURITY;
ALTER TABLE held_bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE return_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE return_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE supplier_returns ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_order_items ENABLE ROW LEVEL SECURITY;

-- Permissive client-side policies for retail POS terminals & Admin Portal
-- Note: In production, configure role-based JWT claims as needed
CREATE POLICY "Permissive select for all clients" ON operators FOR SELECT USING (true);
CREATE POLICY "Permissive modify for all clients" ON operators FOR ALL USING (true);

CREATE POLICY "Permissive all on products" ON products FOR ALL USING (true);
CREATE POLICY "Permissive all on product_batches" ON product_batches FOR ALL USING (true);
CREATE POLICY "Permissive all on confection_categories" ON confection_categories FOR ALL USING (true);
CREATE POLICY "Permissive all on suppliers" ON suppliers FOR ALL USING (true);
CREATE POLICY "Permissive all on sales_invoices" ON sales_invoices FOR ALL USING (true);
CREATE POLICY "Permissive all on sales_items" ON sales_items FOR ALL USING (true);
CREATE POLICY "Permissive all on payment_tenders" ON payment_tenders FOR ALL USING (true);
CREATE POLICY "Permissive all on cash_sessions" ON cash_sessions FOR ALL USING (true);
CREATE POLICY "Permissive all on cash_movements" ON cash_movements FOR ALL USING (true);
CREATE POLICY "Permissive all on return_requests" ON return_requests FOR ALL USING (true);
CREATE POLICY "Permissive all on return_items" ON return_items FOR ALL USING (true);
CREATE POLICY "Permissive all on supplier_returns" ON supplier_returns FOR ALL USING (true);
CREATE POLICY "Permissive all on purchase_orders" ON purchase_orders FOR ALL USING (true);
CREATE POLICY "Permissive all on purchase_order_items" ON purchase_order_items FOR ALL USING (true);
CREATE POLICY "Permissive all on staff_members" ON staff_members FOR ALL USING (true);
CREATE POLICY "Permissive all on payroll_disbursements" ON payroll_disbursements FOR ALL USING (true);
CREATE POLICY "Permissive all on held_bills" ON held_bills FOR ALL USING (true);
CREATE POLICY "Permissive all on customers" ON customers FOR ALL USING (true);
CREATE POLICY "Permissive all on store_terminals" ON store_terminals FOR ALL USING (true);
CREATE POLICY "Permissive all on sales_item_batch_allocations" ON sales_item_batch_allocations FOR ALL USING (true);

-- ============================================================================
-- 23. COMPREHENSIVE INITIAL SEED DATA
-- ============================================================================

-- 1. Initial Categories
INSERT INTO confection_categories (slug, name, display_order, color_code, icon_name)
VALUES 
    ('chocolate', 'Chocolates & Truffles', 1, '#78350F', 'Package'),
    ('biscuits', 'Artisan Biscuits', 2, '#B45309', 'Layers'),
    ('drinks', 'Beverages & Frappes', 3, '#0284C7', 'Coffee'),
    ('toffees', 'Toffees & Caramels', 4, '#D97706', 'Sparkles'),
    ('gifts', 'Gift Hampers & Boxes', 5, '#7C3AED', 'Gift'),
    ('others', 'Confection Items', 6, '#64748B', 'Boxes')
ON CONFLICT (slug) DO NOTHING;

-- 2. Initial Terminal Operators
INSERT INTO operators (id, name, handle, email, password_hash, role, pin, status, avatar_color, notes)
VALUES 
    ('11111111-1111-1111-1111-111111111111', 'Chaminda Silva', '@admin', 'admin@chillandchoc.lk', 'admin123', 'ADMIN', '1234', 'Active', 'teal', 'Super Administrator & Store Owner'),
    ('22222222-2222-2222-2222-222222222222', 'Nimal Perera', '@cashier', 'cashier.colombo@chillchoc.lk', NULL, 'CASHIER', '2580', 'Active', 'gold', 'Primary POS Terminal Cashier • Register 01'),
    ('33333333-3333-3333-3333-333333333333', 'Kasun Fernando', '@manager', 'manager.colombo@chillchoc.lk', 'manager123', 'MANAGER', '4321', 'Active', 'indigo', 'Shift Supervisor & Inventory Controller')
ON CONFLICT (handle) DO NOTHING;

-- 3. Initial Store Terminals
INSERT INTO store_terminals (code, name, outlet_name, status)
VALUES 
    ('POS-01', 'Register 01 - Main Cash Register', 'Colombo Flagship Outlet', 'Active'),
    ('POS-02', 'Register 02 - Express Counter', 'Colombo Flagship Outlet', 'Active')
ON CONFLICT (code) DO NOTHING;

-- 4. Initial Suppliers
INSERT INTO suppliers (id, code, name, brand, contact_person, phone, email, address, lead_time_days, status)
VALUES 
    ('44444444-4444-4444-4444-444444444441', 'CBS', 'Choc & Bakers Supplies Lanka', 'Belgian Gold', 'Sunil Mendis', '+94 11 258 4930', 'orders@cbslanka.lk', 'No. 88, Baseline Road, Colombo 09', 2, 'Active'),
    ('44444444-4444-4444-4444-444444444442', 'CSD', 'Ceylon Sweet Distributors', 'Swiss Delight', 'Kamal De Silva', '+94 11 445 9920', 'supply@ceylonsweets.com', 'No. 14, High Level Road, Maharagama', 3, 'Active'),
    ('44444444-4444-4444-4444-444444444443', 'BBL', 'Bakers & Beverage Lanka', 'ChillCraft', 'Ruwan Jayasinghe', '+94 77 334 1100', 'ruwan@bbl.lk', 'No. 22, Kandy Road, Kelaniya', 1, 'Active')
ON CONFLICT (code) DO NOTHING;

-- 5. Initial Staff Members & Sales Reps
INSERT INTO staff_members (id, name, nic, phone, email, role, base_salary, pay_frequency, overtime_rate, status, bank_name, bank_account)
VALUES 
    ('55555555-5555-5555-5555-555555555551', 'Kasun Fernando', '199428371920', '+94 76 555 8899', 'kasun.fernando@chillandchoc.lk', 'Cashier', 55000.00, 'Monthly', 450.00, 'Active', 'Sampath Bank', '1004839201'),
    ('55555555-5555-5555-5555-555555555552', 'Dilshan Madushanka', '199738291039', '+94 72 333 4455', 'dilshan.m@chillandchoc.lk', 'Staff', 45000.00, 'Monthly', 400.00, 'Active', 'Commercial Bank', '8004928190'),
    ('55555555-5555-5555-5555-555555555553', 'Amal Perera', '199283719201', '+94 77 111 2233', 'amal.p@chillandchoc.lk', 'Staff', 48000.00, 'Monthly', 420.00, 'Active', 'Bank of Ceylon', '7709218201'),
    ('55555555-5555-5555-5555-555555555554', 'Nadeesha Silva', '199583719202', '+94 71 888 9900', 'nadeesha.s@chillandchoc.lk', 'Staff', 46000.00, 'Monthly', 400.00, 'Active', 'Hatton National Bank', '4401928301'),
    ('55555555-5555-5555-5555-555555555555', 'Chamari Silva', '199128374619', '+94 75 444 3322', 'chamari.s@chillandchoc.lk', 'Manager', 75000.00, 'Monthly', 600.00, 'Active', 'Commercial Bank', '8012938491')
ON CONFLICT DO NOTHING;

-- 6. Initial Core Confectionery Products
INSERT INTO products (id, name, sku, barcode, category_slug, weight, price, cost_price, stock, low_stock_threshold, brand, supplier_id)
VALUES 
    ('66666666-6666-6666-6666-666666666661', 'Dark Truffle Noir 70%', 'SKU-CHOC-001', '893450001', 'chocolate', '100g', 850.00, 520.00, 48, 10, 'Belgian Gold', '44444444-4444-4444-4444-444444444441'),
    ('66666666-6666-6666-6666-666666666662', 'Almond Rocher Gold', 'SKU-CHOC-002', '893450002', 'chocolate', '150g', 1200.00, 780.00, 32, 8, 'Belgian Gold', '44444444-4444-4444-4444-444444444441'),
    ('66666666-6666-6666-6666-666666666663', 'Salted Caramel Chews', 'SKU-TOFF-001', '893450003', 'toffees', '200g', 650.00, 390.00, 60, 15, 'Ceylon Sweet', '44444444-4444-4444-4444-444444444442'),
    ('66666666-6666-6666-6666-666666666664', 'Butter Crisp Wafers', 'SKU-BISC-001', '893450004', 'biscuits', '180g', 550.00, 320.00, 40, 10, 'Ceylon Sweet', '44444444-4444-4444-4444-444444444442'),
    ('66666666-6666-6666-6666-666666666665', 'Belgian Dark Choc Ganache', 'SKU-CHOC-003', '893450005', 'chocolate', '1 kg', 4200.00, 3500.00, 15, 5, 'Belgian Gold', '44444444-4444-4444-4444-444444444441'),
    ('66666666-6666-6666-6666-666666666666', 'Iced Mochaccino Blend', 'SKU-DRNK-001', '893450006', 'drinks', '350ml', 480.00, 220.00, 55, 12, 'ChillCraft', '44444444-4444-4444-4444-444444444443'),
    ('66666666-6666-6666-6666-666666666667', 'Royal Velvet Hamper Box', 'SKU-GIFT-001', '893450007', 'gifts', 'Set', 3500.00, 2100.00, 18, 5, 'Chill & Choc Gifts', '44444444-4444-4444-4444-444444444441')
ON CONFLICT (sku) DO NOTHING;

-- 7. Initial Product Batches
INSERT INTO product_batches (product_id, supplier_id, supplier_name, batch_number, cost_price, selling_price, quantity_received, quantity_remaining, received_date, expiry_date)
VALUES 
    ('66666666-6666-6666-6666-666666666661', '44444444-4444-4444-4444-444444444441', 'Choc & Bakers Supplies Lanka', 'LOT-CBS-8803', 520.00, 850.00, 50, 48, CURRENT_DATE - INTERVAL '10 days', CURRENT_DATE + INTERVAL '120 days'),
    ('66666666-6666-6666-6666-666666666662', '44444444-4444-4444-4444-444444444441', 'Choc & Bakers Supplies Lanka', 'LOT-CBS-8804', 780.00, 1200.00, 35, 32, CURRENT_DATE - INTERVAL '15 days', CURRENT_DATE + INTERVAL '180 days'),
    ('66666666-6666-6666-6666-666666666665', '44444444-4444-4444-4444-444444444441', 'Choc & Bakers Supplies Lanka', 'LOT-CBS-8805', 3500.00, 4200.00, 15, 15, CURRENT_DATE - INTERVAL '5 days', CURRENT_DATE + INTERVAL '45 days')
ON CONFLICT DO NOTHING;

-- ============================================================================
-- END OF CHILL & CHOC SUPABASE SCHEMA
-- ============================================================================
